### ISSUE TITLE
Question: best way to keep user state on refresh page?

### ISSUE THREAD

**Issue by RobinTHOREL** [anthonygore/vue-router-user-roles#11]
I've just implemented this library on my first apollo/vue project :fire:

I love the way you thinked your lib <3 but still have a question! And I think I'll not be the unique one with this question. 

After login an user and provide his payload on the $user what's your recommendation to keep the user logged in ($user hydrated) also with browser refresh ?

I've thinked to keep my user's JWT's token on the localStorage and at each refresh just query my API to verify the JWT and re-populate my data on $user. 

Another practice or maybe a good practice ?? :smile: 

PS : I can probably contributing to your documentation to add this point. It can be helpfull for other developers who want to implement your lib. 

Cheers <3

**Comment by anthonygore** [comment]
Hi Robin.

 I think this might be out of the scope of the library because the intention is that it is token/auth agnostic. Once we start to consider the token the library because very similar to Vue Auth.

To answer your question, though, you can store your token as a cookie or in localStorage and check for it when the app boots. It's a good idea to consider the security implications, though.

**Comment by RobinTHOREL** [comment]
Thanks for ur logic reply :heart:
